# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/worker.proto

require 'google/protobuf'


descriptor_data = "\n\x13protos/worker.proto\x12\x06worker\" \n\rWorkerRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\"1\n\x0eWorkerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t2M\n\rWorkerService\x12<\n\x0bPerformTask\x12\x15.worker.WorkerRequest\x1a\x16.worker.WorkerResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Worker
  WorkerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("worker.WorkerRequest").msgclass
  WorkerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("worker.WorkerResponse").msgclass
end
